### ISSUE TITLE
No fractional scaling support under Wayland.

### ISSUE THREAD

**Issue by RayJW** [loft-sh/devpod#788] opened 2023-10-30 14:58 UTC
**What happened?**  

Due to the decision to drop the .deb and .rpm packages, there is no more fractional scaling support under Wayland because AppImages struggle with that.

**What did you expect to happen instead?**  

Support fractional scaling, so the application doesn't look blurry.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Set scaling factor to something else than 1.0 on a HiDPI screen and launch DevPod under Wayland.

**Local Environment:**  
- DevPod Version: 0.4.0
- Operating System: Fedora 38
- ARCH of the OS: AMD64

**Anything else we need to know?**  

I personally think, for such issues "package it yourself" is not a valid answer, but if that is what you want to go with, like with deb and rpm packages, I respect that decision. But it makes the application unusable on a modern Linux dev environment, in my opinion.

**Comment by AnhQuanTrl** [comment] 2024-01-17 08:20
I believe the issue is that DevPod run as xwayland app instead of native wayland. I have tested it using `xeyes`.
I am not really fluent with tauri tbh. With electron I can force the app to use wayland by setting some ozone environment variables.
https://github.com/tauri-apps/tauri/issues/4635 This issue seems related, but probably already fixed in an older tauri version.
Also, I took a look at the tauri repo's issues list and it seems a lot of users can run tauri apps as native wayland already??

**Comment by RayJW** [comment] 2024-01-18 12:55
Yes that is indeed the problem, however I don't think it's Tauri related. Tauri apps should work fine when distributed any other way than AppImage (the rpm they used to have works fine with native Wayland). The problem is AppImages, the developer has some weird unjustified stance against Wayland and thus single-handedly holds back AppImages working natively with Wayland, see this [PR](https://github.com/probonopd/linuxdeployqt/pull/540).

**Closed** 2024-01-22 14:29 UTC
Labels: kind/bug
