### ISSUE TITLE
Blank screen when launching devpod on Linux

### ISSUE THREAD

**Issue by adamryczkowski** [loft-sh/devpod#407] opened 2023-06-21 08:11 UTC
**What happened?**
Blank windows with no UI after launching the devpod on my machine (for the first time).

**What did you expect to happen instead?**
See some form of UI with text, buttons and frames.

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. Download the `DevPod_linux_amd64.deb` and install it using e.g. gdebi
2. Run `dev-pod` or alternatively: `dev-pod --disable-gpu`

My `devcontainer.json` is irrelevant here. I never went so far to have any kind of interaction with the app.

**Local Environment:**

* DevPod Version: v0.1.9
* Operating System: linux
* ARCH of the OS: AMD64

I run an optimus notebook with AMD CPU and NVidia GPU, configured as "on-demand" (`prime-select query` == on-demand). That probably means that some applications assume I have the GPU, while the system inhibits its use. The most conspicuous offender is Chrome (which I have to launch with --disable-gpu flag) and consequently any application built on top of its engine, like e.g. MS Teams or VS Code.

**Comment by pascalbreuninger** [comment] 2023-06-21 08:18
Hi @adamryczkowski , thanks for opening the issue, we'll look into it. Which linux distro are you running?

**Comment by adamryczkowski** [comment] 2023-06-21 08:19
Ubuntu 22.04 64bit. My window manager is i3.

**Comment by adamryczkowski** [comment] 2023-06-21 08:28
One more thing: I've just noticed, that after the app is still running, displaying the icon in the system tray area:
![image](https://github.com/loft-sh/devpod/assets/4469707/c244d2b3-0daa-4515-aa2e-e0926f86d662)

The icon is responsive, showing a short context menu: "Show Dashboard", "Workspaces" -> "Create Workspace" and "Quit". Clicking the "Quit" exists the app. I believe it is a pure UI issue, solvable if you forward the command line arguments to the Electron/Chrome UI backend.

**Comment by pascalbreuninger** [comment] 2023-06-21 09:27
DevPod is built on tauri so it should use the webkit webview on your system, not chrome. What happens if you try to open the UI via system tray -> show dashboard?

**Comment by adamryczkowski** [comment] 2023-06-21 16:03
Thank you for mentioning the Tauri. That made me do this trick:
```
$ export WEBKIT_DISABLE_COMPOSITING_MODE=1
$ dev-pod
```

...and finally: my first ever local view of the app. Now I can start evaluating it :-) 

![image](https://github.com/loft-sh/devpod/assets/4469707/224ea4ca-43bf-4675-9efc-7b494bb09b32)

**Comment by pascalbreuninger** [comment] 2023-06-21 16:57
Oh wow, I would never have discovered that :D Glad you figured it out.

I'll close this issue if you don't mind

**Closed by pascalbreuninger** 2023-06-21 16:57 UTC

**Comment by nneto** [comment] 2024-07-29 21:29
I had the same issue. The issue is closed but won't that keep happening to other people if it isn't fixed?
