### ISSUE TITLE
devpod crashes when building a local feature

### ISSUE THREAD

**Issue by rokroskar** [loft-sh/devpod#589] opened 2023-08-02 20:03 UTC
**What happened?**

Ran `devpod up` in a project with a small local feature and the build crashed with

```
$ devpod up --debug --provider docker .                                                                                                    
21:48:34 debug Acquire workspace lock...
21:48:34 debug Acquired workspace lock...
21:48:34 info Creating devcontainer...
21:48:34 debug Inject and run command: '/usr/local/bin/devpod' agent workspace up --debug
21:48:34 debug Execute command locally
21:48:34 info Use /Users/rok/.devpod/agent/contexts/default/workspaces/devpod-remoteuser as workspace dir
21:48:34 debug Created logger
21:48:34 debug Received ping from agent
21:48:34 debug Workspace Folder already exists
21:48:34 debug Using docker command 'docker'
21:48:34 debug Process local feature
21:48:34 debug Parse dev container feature in /tmp/devpod-remoteuser/.devcontainer/adduser
21:48:34 info lchown /var/folders/99/jng0jljd13db0h4jwbwtx4mh0000gn/T/devpod2882746750/0/devcontainer-feature.json: operation not permitted
21:48:34 info copy feature ./adduser
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer/feature.copyFeaturesToDestination
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/feature/extend.go:156
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer/feature.getFeatureBuildOptions
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/feature/extend.go:98
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer/feature.GetExtendedBuildInfo
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/feature/extend.go:81
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).buildAndExtendImage
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/build.go:83
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).build
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/build.go:18
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runSingleContainer
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/single.go:44
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/run.go:131
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:393
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:164
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:98
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:57
21:48:34 info github.com/spf13/cobra.(*Command).execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:48:34 info github.com/spf13/cobra.(*Command).ExecuteC
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:48:34 info github.com/spf13/cobra.(*Command).Execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:48:34 info github.com/loft-sh/devpod/cmd.Execute
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/root.go:89
21:48:34 info main.main
21:48:34 info   /Users/runner/work/devpod/devpod/main.go:8
21:48:34 info runtime.main
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:48:34 info runtime.goexit
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
21:48:34 info get extended build info
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).buildAndExtendImage
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/build.go:85
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).build
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/build.go:18
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runSingleContainer
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/single.go:44
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/run.go:131
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:393
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:164
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:98
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:57
21:48:34 info github.com/spf13/cobra.(*Command).execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:48:34 info github.com/spf13/cobra.(*Command).ExecuteC
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:48:34 info github.com/spf13/cobra.(*Command).Execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:48:34 info github.com/loft-sh/devpod/cmd.Execute
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/root.go:89
21:48:34 info main.main
21:48:34 info   /Users/runner/work/devpod/devpod/main.go:8
21:48:34 info runtime.main
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:48:34 info runtime.goexit
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
21:48:34 info build image
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runSingleContainer
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/single.go:51
21:48:34 info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
21:48:34 info   /Users/runner/work/devpod/devpod/pkg/devcontainer/run.go:131
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:393
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:164
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:98
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:57
21:48:34 info github.com/spf13/cobra.(*Command).execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:48:34 info github.com/spf13/cobra.(*Command).ExecuteC
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:48:34 info github.com/spf13/cobra.(*Command).Execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:48:34 info github.com/loft-sh/devpod/cmd.Execute
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/root.go:89
21:48:34 info main.main
21:48:34 info   /Users/runner/work/devpod/devpod/main.go:8
21:48:34 info runtime.main
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:48:34 info runtime.goexit
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
21:48:34 info devcontainer up
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:100
21:48:34 info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:57
21:48:34 info github.com/spf13/cobra.(*Command).execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
21:48:34 info github.com/spf13/cobra.(*Command).ExecuteC
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
21:48:34 info github.com/spf13/cobra.(*Command).Execute
21:48:34 info   /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
21:48:34 info github.com/loft-sh/devpod/cmd.Execute
21:48:34 info   /Users/runner/work/devpod/devpod/cmd/root.go:89
21:48:34 info main.main
21:48:34 info   /Users/runner/work/devpod/devpod/main.go:8
21:48:34 info runtime.main
21:48:34 debug Done executing up command
21:48:34 debug Done creating devcontainer
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
21:48:34 info runtime.goexit
21:48:34 info   /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
21:48:34 fatal executing agent command: exit status 1
```

**What did you expect to happen instead?**

Build the image and launch the container.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
    "image": "ubuntu",
    "remoteUser": "auser",
    "features": {
        "./afeature": {}
    }
}
```

in the `afeature` directory:

`devcontainer-feature.json`:

```
{
    "name": "A feature",
    "id": "afeature",
    "version": "1.0.0",
    "description": "A feature.",
    "options": {}
}
```

`install.sh`:

```
#!/bin/bash

useradd -l -m -s /bin/bash -N -u 1000 "auser"
```

**Local Environment:**

* DevPod Version: v0.3.3
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: docker

**Comment by neogopher** [comment] 2023-08-03 11:06
Hi @rokroskar :wave: ,
Can you please check the ownership of the directory containing the devcontainer.json i.e. "/tmp/devpod-remoteuser", whether its different than the user you are running with.

**Comment by rokroskar** [comment] 2023-08-03 11:26
Hi @neogopher thanks for getting back to me - it's owned by the user invoking the `devpod` command - I assume that's what you mean?

**Comment by neogopher** [comment] 2023-08-03 12:21
Yes. That's correct. 
I was only able to reproduce this issue if I changed the owner of the directory or at least the file "/tmp/devpod-remoteuser/.devcontainer/afeature/devcontainer-feature.json" to some other user such as root.

**Comment by rokroskar** [comment] 2023-08-03 12:49
Strange. In my case all the files (and directories) have the correct ownership. I tried moving it out of `/tmp` to my home directory but got the same error. Are you also on macOS?

**Comment by neogopher** [comment] 2023-08-03 13:03
Ahh. I am trying this on a Linux amd64 machine. But, I will also check and see if I can reproduce this issue on a Mac.

**Comment by neogopher** [comment] 2023-08-04 10:06
Hi @rokroskar . We tried this on a Mac too and were not able to reproduce it. I am puzzled and really out of ideas on what else we can try to debug your issue.

**Comment by rokroskar** [comment] 2023-08-04 13:02
Ok thanks for checking @neogopher. I'll try to nuke everything on my side and give it another go. Just to be sure, you were using the same version (0.3.3), correct?

**Comment by neogopher** [comment] 2023-08-09 07:20
Hi @rokroskar, 
Were you able to try it out by starting afresh. Does it work for you now.

**Comment by rokroskar** [comment] 2023-08-10 16:17
Hi @neogopher, I had to set up a new directory with a new devcontainer feature etc. and eventually it worked. Uninstalling and reinstalling devpod wasn't enough... I guess some cache stuck around.

**Comment by neogopher** [comment] 2023-08-11 05:44
Ahh!! But I am really glad you got it working. :slightly_smiling_face: 
I will close this issue for now. But feel free to write back to us in case you face any issues again with this.

**Closed by neogopher** 2023-08-11 05:44 UTC
Labels: bug, kind/bug
