### ISSUE TITLE
Devpod machine created from cli does not respect inactivity timeout

### ISSUE THREAD

**Issue by famagusta** [loft-sh/devpod#901] opened 2024-02-14 05:18 UTC
I created a devpod machine from the CLI

`devpod machine create test`

The machine.json file lists an inactivity timeout of 5m. But this is not respected. Machine is still in running status after 16h.

Is this behaviour expected?

**Comment by pascalbreuninger** [comment] 2024-02-15 09:49
Hey @famagusta, thanks for opening the issue. Could you provider a bit more context here please? 
What host operating system are you on, which provider do you use and which DevPod version are you on?

**Comment by famagusta** [comment] 2024-02-15 11:08
Sure. I tested i below configurations with AWS Provider (ap-south-1 region) using t3.medium & t3a.medium

MacOS 12.4 with devpod version 0.5.0
Ubuntu 22.04 with devpod version 0.5.2

In all the above, I didn't see the machine stopping after inactivity timeout

**Comment by 89luca89** [comment] 2024-02-23 12:02
Hi @famagusta 

Are you able to verify if this happens if you use `devpod up ..` instead of `devpod machine create`?
I was not able to reproduce with `up`, but I noticed that some variables are not correctly picked up with `machine create` so I was wondering maybe that is one of the issue

**Comment by famagusta** [comment] 2024-02-27 03:29
I will test it once

**Comment by pascalbreuninger** [comment] 2024-03-06 06:38
@famagusta I'll close the issue then if that's alright. We even thought about hiding the `machine create/stop/start` commands because they are mostly intended for troubleshooting and management, not to enforce workspace behaviour... They'd still be usable but not discoverable via the CLI help

**Closed by pascalbreuninger** 2024-03-06 06:38 UTC
Labels: kind/bug, wait for user

**Comment by famagusta** [comment] 2024-03-07 09:07
Sure, np. We were trying to use devpods just as a aws machine orchestrator for our developers. We didn't want the workspaces as of now. We were relying on devpods to timeout and stop the machines.
We achieved the same thing using one of the prebuilt workspace as a placeholder.

**Comment by pascalbreuninger** [comment] 2024-03-07 12:49
I see, maybe you can work around this by having an empty git repository as the workspace?
It's not exactly the main use-case of DevPod to orchestrate machines that's why I'd rather keep this low-key
