### ISSUE TITLE
Double clicking the notification area icon on Windows doesn't open the window

### ISSUE THREAD

**Issue by MartinAskestad** [loft-sh/devpod#1302] opened 2024-10-06 11:03 UTC
**What happened?**  
When double clicking the notification area icon (sys tray icon), the usual thing that happens on Windows is that the application window opens, but the devpod app windows doesn't show up.

**What did you expect to happen instead?**  
The devpod app window opens.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run on Windows, double click the notification area icon.

**Local Environment:**  
- DevPod Version: [use `devpod version`]
- Operating System: windows
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider: google | aws | azure | digitalOcean
- Kubernetes Provider: [use `kubectl version`]
- Local/remote provider: docker | ssh
- Custom provider: provide imported `provider.yaml` config file

**Anything else we need to know?**

**Comment by haukex** [comment] 2024-10-07 11:58
I just noticed this issue, it seems to be a duplicate of my issue #1280.

**Comment by MartinAskestad** [comment] 2024-10-07 12:12
> I just noticed this issue, it seems to be a duplicate of my issue #1280.

I think you are right.

**Comment by pascalbreuninger** [comment] 2024-11-25 07:59
@haukex @MartinAskestad I'll close this issue as a duplicate, thanks for opening it anyway

**Closed by pascalbreuninger** 2024-11-25 07:59 UTC
Labels: kind/bug, windows
