### ISSUE TITLE
devpod process does not end even after closing the app

### ISSUE THREAD

**Issue by robinhalabicki** [loft-sh/devpod#750] opened 2023-10-19 20:14 UTC
**What happened?**  
CPU Running at %30+ even after closing devpod app

**What did you expect to happen instead?**  
Process to end

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run devpod even with no pods running.    Close the app, Windows Defender will start using CPU and will not release it until the devpod process is "Ended" manually via "End Task" in task manager.   CPU will immediately drop after process is ended

**Local Environment:**  
- DevPod Version: 0.3.7
- Operating System: windows 11 22H2
- ARCH of the OS: x86

**Comment by pascalbreuninger** [comment] 2023-10-20 08:55
DevPod Desktop stays in the background as a system tray application, so I suspect that's the "leftover" process you're experiencing. 
The high cpu usage on windows is a separate issue we'll need to look into, it's a duplicate of #457 I assume

**Closed by pascalbreuninger** 2023-10-20 08:55 UTC
Labels: kind/bug
