### ISSUE TITLE
Ignore gitignored files when uploading

### ISSUE THREAD

**Issue by skorfmann** [loft-sh/devpod#677] opened 2023-09-04 09:23 UTC
**Is your feature request related to a problem?**  

When a project has lots of dependencies / build artifacts in the local project folder, uploading them to the remote instance might take quite a while and upload data which is likely not usable for the remote OS anyway.

![Screenshot 2023-09-04 at 11 22 35](https://github.com/loft-sh/devpod/assets/136789/e1963fd6-4d1a-42cb-929a-624b3300468a)

**Which solution do you suggest?**  

Ignore files for upload which are ignored via `.gitignore`

**Which alternative solutions exist?**  

run `git clean -fdx` in the project before creating the workspace  - which might not be desirable / pretty inconvenient.

**Additional context**

**Comment by FabianKramm** [comment] 2023-09-04 13:43
@skorfmann thanks a lot for creating this issue! Mhhh yeah I can see this being a problem for some projects, but there are others where excluding gitignored files is not wanted, e.g. certain .env files or custom configuration you might want to sync. I'm sure how we would approach this the best way, but we could maybe add an option to exclude .gitignored files.

**Comment by skorfmann** [comment] 2023-09-04 14:53
yes, makes sense. A config might be an option

**Comment by s-vamshi** [comment] 2023-10-08 01:05
@skorfmann I would like to work on this issue

**Comment by ShivamAgarwal-code** [comment] 2023-10-25 11:02
@skorfmann I would like to work on this issue, kindly assign me..

**Comment by skorfmann** [comment] 2023-10-25 11:03
Not a maintainer of this project, just created this issue

**Comment by bkneis** [comment] 2024-10-15 12:51
Duplicate of https://github.com/loft-sh/devpod/issues/1299

**Closed by bkneis** 2024-10-15 12:51 UTC
Labels: good first issue, help wanted
