### ISSUE TITLE
Opening workspaces in DevPod using browser links no longer works?

### ISSUE THREAD

**Issue by dbarvitsky** [loft-sh/devpod#748] opened 2023-10-19 16:18 UTC
First off, I've been using a bash script and a combination of vs code hacks to achieve "reproducible and standardized dev environment". It has been a side project for years, with mixed success and limited adoption throughout my company. DevPod is a huge step forward, thank you very much for working on it!

**What happened?**  

This morning, right when I was about to do a demo to the team... I noticed that links links for opening the workspaces from the browser (`https://devpod.sh/open#https://github.com/loft-sh/devpod`), a.k.a "Open in DevPod" no longer work. The DevPod is no longer called to open a workspace. Instead the "We opened DevPod on your machine. You can close this tab." page is shown and nothing happens.

**What did you expect to happen instead?**  

The workspace should be loaded in DevPod, or at least some reasonable error messages given to the user.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Try opening `https://devpod.sh/open#https://github.com/loft-sh/devpod`.

**Local Environment:**  
- DevPod Version: `0.3.7` (also tried 2 previous releases)
- Operating System: max
- ARCH of the OS: AMD64

**DevPod Provider:**  
- irrelevant

**Anything else we need to know?**  

Debugging the "We opened DevPod on your machine" web page in Chrome reveals several JS errors:
- 404 for `https://devpod.sh/js/open.js`
- 403 for `https://tag.clearbitscripts.com/v1/pk_f37b5315c26dfeb44a2d121ed020a811/tags.js`
- "Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set."

Attempted workarounds:
- Tried changing the URL to `devpod:...` directly, the DevPod is actually launched, but fails with "UnsupportedHost: no host". I guess I didn't get the URL syntax right, and couldn't really figure out what it is supposed to be  from source.
- Installing / uninstsalling / upgrading / downgrading GitPod - seems to be irrelevant, looks like the landing page itself is broken.

Suggested fixes:
- It would be nice to stay true to the nature of "client-only" DevPod approach and avoid loading stuff in the landing page from other places. This reduces the possibility of JS failing to load and suchlike.
- The landing page should display the CLI command (a la `devpod up <url>`) to launch the workspace in case the mime registration doesn't work or browser is restricted from opening the apps. At very least you give user a workaround to try.
- It would be nice to document the protocol for the `devpod:...` links perhaps to avoid going to the third party URLs in first place. I.e. specifying a branch through the URL would be a very useful thing for us.

**Comment by pascalbreuninger** [comment] 2023-10-20 08:40
Hi @dbarvitsky, thanks for opening the issue and sorry for the downtime.
It was caused by an update to our website. It's fixed now and we changed the flow, so that it won't happen again.

The redirect via `devpod.sh` is mainly for convenience and compatibility. Github for example doesn't let you launch a custom deep link from markdown files. You're right in that it's hard to build a deep link yourself now, so [here](https://github.com/loft-sh/devpod/blob/main/CONTRIBUTING.md#deeplinks) is some more documentation.

> The landing page should display the CLI command (a la devpod up <url>) to launch the workspace in case the mime registration doesn't work or browser is restricted from opening the apps. At very least you give user a workaround to try.

Good idea, added `devpod up $SOURCE` to the redirect page.

>  It would be nice to document the protocol for the devpod:... links perhaps to avoid going to the third party URLs in first place. I.e. specifying a branch through the URL would be a very useful thing for us.

Not sure how the later part of this relates to the first one, but you can open branches in DevPod like so: `devpod up github.com/$ORG/$REPO@$BRANCH_NAME `

**Closed by pascalbreuninger** 2023-10-20 08:40 UTC
Labels: kind/bug

**Comment by dbarvitsky** [comment] 2023-10-20 15:06
@pascalbreuninger Thank you!
