### ISSUE TITLE
Error creating workspace using the node.js template 

### ISSUE THREAD

**Issue by bitsByB** [loft-sh/devpod#857] opened 2024-01-03 00:08 UTC
hi there,
I'm using the node.js template with jupyter lab and docker.
the install hangs at this point:
```
[18:36:21] info Workspace vscode-remote-try-node already exists [18:36:21] info Creating devcontainer...
[18:36:22] info Setup container...
[18:36:22] info seems like neither pip3 nor pip exists, please make sure to install python correctly
[18:36:22] info devcontainer up: run agent command: Process exited with status 1
[18:36:22] error Try enabling Debug mode under Settings to see a more verbose output
[18:36:22] fatal run agent command: Process exited with status 1
```
![image](https://github.com/loft-sh/devpod/assets/102392085/887d0efd-ef26-4dc3-87c5-2aba28015659)

**Local Environment:**  
- DevPod Version: 0.4.2
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local: docker

Any idea of what's going on? the whole process should go through without me doing anything right?
or I'm missing something... :|
Thanks

**Comment by pascalbreuninger** [comment] 2024-01-03 06:18
@bitsByB thanks for opening the issue, could you enable the debug logs and paste them here please?

**Comment by bitsByB** [comment] 2024-01-03 15:55
hey Pascal, thanks for helping me, here's what I'm getting:

![image](https://github.com/loft-sh/devpod/assets/102392085/ec64e3ce-37b6-47b0-874d-d5584018ab59)

**Comment by pascalbreuninger** [comment] 2024-01-03 16:33
the problem is that you're trying to open a workspace with jupyter notebooks that doesn't have python installed - either add it to you devcontainer image or change the IDE to something like `vscode-browser`

**Comment by bitsByB** [comment] 2024-01-03 17:53
ok I understand so I download the template zip and add to the devcontainer.json:
```
// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "yarn install"
```
can I add :
```
postCreateCommand": "yarn pip3 python3 install"
```
or should it be :
```
postCreateCommand": "yarn install" "pip3 install" "python3 install"
```
?
thanks

**Comment by bitsByB** [comment] 2024-01-03 20:23
none of it works anyway:
![image](https://github.com/loft-sh/devpod/assets/102392085/d6e86db0-9b2d-411d-a535-fa869f819235)
with:
```
// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "pip3 install && python3.10 install && yarn install"
```

**Comment by bitsByB** [comment] 2024-01-03 20:33
My  goal is to be able to use javascript in the jupyter notebook. thanks for your help @pascalbreuninger

**Comment by pascalbreuninger** [comment] 2024-01-04 06:05
I'm not exactly sure about how to set this up. 
But here is how I'd start:
1. Use a baseline jupyter notebooks devcontainer like [this one](https://github.com/github/codespaces-jupyter) 
2. Install additional javascript dependencies using the `postCreateCommand` like you did or check the base image, most likely it's already preinstalled

For the time being I'd close this issue as it's a question of configuration, not a bug

**Closed by pascalbreuninger** 2024-01-04 06:05 UTC
Labels: kind/bug
