### ISSUE TITLE
DevPod 0.3.7 fails to install extensions with VSCode Insiders

### ISSUE THREAD

**Issue by dbarvitsky** [loft-sh/devpod#774] opened 2023-10-24 16:00 UTC
Once again, thank you very much for continuing to support DevPod!

**What happened?**  

I have a project with a `vscode` extensions in `./devcontainer/devcontainer.json` as follows:

```json
{
  "name": "irrelevant",
  "dockerComposeFile": "./docker-compose.yaml",
  "service": "irrelevant",
  "workspaceFolder": "/src",  
  "customizations": {
    "vscode": {
      /* spell-checker: ignore scalameta l13rary devcontainer sodatea */
      "extensions": [
        "streetsidesoftware.code-spell-checker",
        "scalameta.metals",
        "l13rary.l13-diff",
        "redhat.vscode-xml",
        ...
      ],
    settings: {...}
}
```

The IDE in DevPod is set to `VSCode`. The local IDE (and this is important) is the VSCode Insiders (that's a pre-release build of VSCode).

The workspace starts as expected, and prints the "Installing extensions in background" message when run with debug. Upon start-up, however, the extensions are not installed on the remote host.

**What did you expect to happen instead?** 

The extensions should have been installed, or the DevPod should fail starting the workspace and report that VSCode Insiders is not supported.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Please use the devcontainer config from above on the system that has VSCode Insiders installed. The actual extensions do not matter. 

**Local Environment:**  
- DevPod Version: `0.3.7`
- Operating System: mac
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Cloud Provider:none (irrelevant)
- Kubernetes Provider: none (irrelevant)
- Local/remote provider: docker (irrelevant)
- Custom provider: none

**Anything else we need to know?**

In my case (mac) the `/usr/local/bin/code` was pointing to the `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code`, which is why DevPod picked it up as VSCode instance. In all fairness It might have been my environment issue: I've been on the insiders build for ages, and the peculiar code symlinking might have happened historically.

The VSCode Insiders tends to append `-insiders` to some paths, notably remote workspace server path is `/vscode/vscode-server-insiders`. Per [source](https://github.com/loft-sh/devpod/blob/main/pkg/ide/vscode/vscode.go#L162) the hardcoded path `vscode-server` doesn't match what is actually there in container if VSCode Insiders is used, perhaps that has something to do with it.

**Workaround**
Fixing the `/usr/local/bin/code` and pointing it to non-Insiders install of the VSCode allowed me to move on.

Having said that, it would be nice to be able to use DevPod with VSCode Insiders, at least for the reason of supporting the VSCode dev community. From my past experience with them, they do care about telemetry they collect from the Insiders build quite a bit. I'd imagine some checkbox somewhere in settings, or at least a non-UI-surfaced option in the `~/.devpod/config.yaml` would suffice.

Thank you!

**Comment by 89luca89** [comment] 2023-10-25 08:19
This should be a duplicate of #310 then
We should add the VSCode Insiders to the list of IDEs in order to support this properly

**Closed** 2023-10-25 09:15 UTC
Labels: kind/bug
